chore: use $* for better style in expansion
shellcheck is happier this way, even if it should work the same way.

diff --git a/check b/check
--- a/check
+++ b/check
@@ -58,7 +58,7 @@ code() {
 }
 
 panic() {
-    echo "ERROR: $@" 1>&2
+    echo "ERROR: $*" 1>&2
     exit 1
 }
 
